schema = 1

[mod]
  [mod."github.com/alecthomas/template"]
    version = "v0.0.0-20190718012654-fb15b899a751"
    hash = "sha256-RsS4qxdRQ3q+GejA8D9Iu31A/mZNms4LbJ7518jWiu4="
  [mod."github.com/alecthomas/units"]
    version = "v0.0.0-20190717042225-c3de453c63f4"
    hash = "sha256-vho02JWLkLST8oBHdWufpXZxoDSkCUVkMP6M/eg/Q0s="
  [mod."github.com/apple/foundationdb/bindings/go"]
    version = "v0.0.0-20220610181231-8321c6f16d70"
    hash = "sha256-bsUJhukoS4ltiiIC4dt9ZNZnX5q7vryzTIxno2kg61M="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.1.1"
    hash = "sha256-cF+sDnnTZ1xRwjsy08SVSV/JoZalwY+dg0Zkghy6BNw="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/go-kit/kit"]
    version = "v0.9.0"
    hash = "sha256-dcW5++iYlt0zxgaZTpWXKl8LX4/npy+MadnXXmzzRUo="
  [mod."github.com/go-logfmt/logfmt"]
    version = "v0.4.0"
    hash = "sha256-qX6aMMNTmN+D7LtQLZxW/LAKxRpze4vO77F2EQLrVRs="
  [mod."github.com/go-stack/stack"]
    version = "v1.8.0"
    hash = "sha256-26RlTEcAkbewMUtmirKrDGQ1WJlNousp69v7HMopYnI="
  [mod."github.com/gogo/protobuf"]
    version = "v1.1.1"
    hash = "sha256-AmlVpKOrFGBUTVR7J5grNUlVJ3hiJcHY8nq+jDRV26s="
  [mod."github.com/golang/protobuf"]
    version = "v1.3.2"
    hash = "sha256-4fGAPuXMGpohqcqHeoIHwzCvkiWtIOAs0ewIhZ8JeU8="
  [mod."github.com/google/go-cmp"]
    version = "v0.3.1"
    hash = "sha256-oUPl5ojctSzSgOSdWB3HeQ5NOcTFtXly7HLSC2IiXLE="
  [mod."github.com/google/gofuzz"]
    version = "v1.0.0"
    hash = "sha256-ZvgcSQt4kMwS6nvPp3jrlCHSH3bky1oBD6kytnEa5GM="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.8"
    hash = "sha256-/GIhrQGyFbiuMIsH+Jp95Pa8W7fPySd0MUBP0oRV/v0="
  [mod."github.com/julienschmidt/httprouter"]
    version = "v1.2.0"
    hash = "sha256-xhj9PYKNIfQ/CQb8/3O3OtBmiIAJYtiL23cTnRj1C80="
  [mod."github.com/konsorten/go-windows-terminal-sequences"]
    version = "v1.0.1"
    hash = "sha256-Nwp+Cza9dIu3ogVGip6wyOjWwwaq+2hU3eYIe4R7kNE="
  [mod."github.com/kr/logfmt"]
    version = "v0.0.0-20140226030751-b84e30acd515"
    hash = "sha256-CePQbqWGtS8qP/Av9pkLiqZwH6RaZQff/s1l+1//jQo="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.1"
    hash = "sha256-ystDNStxR90j4CK+AMcEQ5oyYFRgWoGdvWlS0XQMDLQ="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.1"
    hash = "sha256-5D1HGVBc/REwPVdlPYcXsbZM80OIh7V5uiyKAbMA5qo="
  [mod."github.com/mwitkow/go-conntrack"]
    version = "v0.0.0-20161129095857-cc309e4a2223"
    hash = "sha256-rgZ2fm0Vi04xGDhkeFPDSZ+KPKi0a/5rerjOdea1eVk="
  [mod."github.com/pkg/errors"]
    version = "v0.8.1"
    hash = "sha256-oe3iddfoLRwpC3ki5fifHf2ZFprtg99iNak50shiuDw="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.3.0"
    hash = "sha256-dijzjjNlypsa+IfjDBFGHiImqSqjdq2k1XohrbffvjI="
  [mod."github.com/prometheus/client_model"]
    version = "v0.1.0"
    hash = "sha256-tKY6KZiuye2Lp4xXtUmiAVA6tfX0L5uIzmP+r1O3mME="
  [mod."github.com/prometheus/common"]
    version = "v0.7.0"
    hash = "sha256-DITh2XqKsf35EXf/do3G+lzCrFw/Pdh0OgSUey9gHik="
  [mod."github.com/prometheus/procfs"]
    version = "v0.0.8"
    hash = "sha256-ty8Jg3Q3it1mgvKRNYbffAJ4C9Dq3SJt6U7DpcsGynI="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.4.2"
    hash = "sha256-3QzWUsapCmg3F7JqUuINT3/UG097uzLff6iCcCgQ43o="
  [mod."github.com/stretchr/objx"]
    version = "v0.1.1"
    hash = "sha256-HdGVZCuy7VprC5W9UxGbDmXqsKADMjpEDht7ilGVLco="
  [mod."github.com/stretchr/testify"]
    version = "v1.3.0"
    hash = "sha256-+mSebBNccNcxbY462iKTNTWmd5ZuUkUqFebccn3EtIA="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20190308221718-c2843e01d9a2"
    hash = "sha256-Gd0WskpyDGdJe9bYBZJU6l/k3UcE3910rDadXOTqrwc="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20190613194153-d28f0bde5980"
    hash = "sha256-KzSX1FBLjGrPRN8MDkuOcWos763nWenxiWfIyqbJtmg="
  [mod."golang.org/x/sync"]
    version = "v0.0.0-20190911185100-cd5d95a43a6e"
    hash = "sha256-ukGj21BvQcm+cQjIkpabFUeFtABQRlFUZXjj4MX3E9s="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20191220142924-d4481acd189f"
    hash = "sha256-8YfNt3QQdx1vZSNQKtgKhhjZO0Llbk9qxHm49pPtgLw="
  [mod."golang.org/x/text"]
    version = "v0.3.0"
    hash = "sha256-0FFbaxF1ZuAQF3sCcA85e8MO6prFeHint36inija4NY="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20200804184101-5ec99f83aff1"
    hash = "sha256-62f++IO8Ia32CYy+xX8XDxCcT9r1sbPvVwoKV99gf7U="
  [mod."gopkg.in/alecthomas/kingpin.v2"]
    version = "v2.2.6"
    hash = "sha256-uViE2kPj7tMrGYVjjdLOl2jFDmmu+3P7GvnZBse2zVY="
  [mod."gopkg.in/check.v1"]
    version = "v0.0.0-20161208181325-20d25e280405"
    hash = "sha256-1w5mgYaZUC52uzDnpXXVqle/9AVkH4WePSrQFOVANUw="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.2.2"
    hash = "sha256-SjNLmGSxoYabOi/zdjymW3mSgaxaS39btBQ3/aUIkgc="
