["github.com/alecthomas/template"]
  sumVersion = "v0.0.0-20190718012654-fb15b899a751"
  ["github.com/alecthomas/template".fetch]
    type = "git"
    url = "https://github.com/alecthomas/template"
    rev = "fb15b899a75114aa79cc930e33c46b577cc664b1"
    sha256 = "1vlasv4dgycydh5wx6jdcvz40zdv90zz1h7836z7lhsi2ymvii26"

["github.com/alecthomas/units"]
  sumVersion = "v0.0.0-20190717042225-c3de453c63f4"
  ["github.com/alecthomas/units".fetch]
    type = "git"
    url = "https://github.com/alecthomas/units"
    rev = "c3de453c63f4bdb4dadffab9805ec00426c505f7"
    sha256 = "0js37zlgv37y61j4a2d46jh72xm5kxmpaiw0ya9v944bjpc386my"

["github.com/apple/foundationdb"]
  sumVersion = "v0.0.0-20210420032056-0511906b887e"
  ["github.com/apple/foundationdb".fetch]
    type = "git"
    url = "https://github.com/apple/foundationdb"
    rev = "0511906b887e6bce5485200b1e569b3cdcd39c5d"
    sha256 = "1nvqbr5jy3yxsfyjiwg7lfgkm1dpzw2hajzq5w49586n2j9s3xhr"

["github.com/apple/foundationdb/bindings/go"]
  sumVersion = "v0.0.0-20211207225159-47b9a81d1c10"
  relPath = "bindings/go"
  ["github.com/apple/foundationdb/bindings/go".fetch]
    type = "git"
    url = "https://github.com/apple/foundationdb"
    rev = "47b9a81d1c10897c863098fe2d66e827fed0d239"
    sha256 = "1kdb52sl8bhg9wzrcww49xmvknxhd2v4n9gcc5ffxsq01a2nashz"

["github.com/beorn7/perks"]
  sumVersion = "v1.0.1"
  ["github.com/beorn7/perks".fetch]
    type = "git"
    url = "https://github.com/beorn7/perks"
    rev = "37c8de3658fcb183f997c4e13e8337516ab753e6"
    sha256 = "17n4yygjxa6p499dj3yaqzfww2g7528165cl13haj97hlx94dgl7"

["github.com/cespare/xxhash/v2"]
  sumVersion = "v2.1.1"
  ["github.com/cespare/xxhash/v2".fetch]
    type = "git"
    url = "https://github.com/cespare/xxhash"
    rev = "d7df74196a9e781ede915320c11c378c1b2f3a1f"
    sha256 = "0rl5rs8546zj1vzggv38w93wx0b5dvav7yy5hzxa8kw7iikv1cgr"

["github.com/davecgh/go-spew"]
  sumVersion = "v1.1.1"
  ["github.com/davecgh/go-spew".fetch]
    type = "git"
    url = "https://github.com/davecgh/go-spew"
    rev = "8991bc29aa16c548c550c7ff78260e27b9ab7c73"
    sha256 = "0hka6hmyvp701adzag2g26cxdj47g21x6jz4sc6jjz1mn59d474y"

["github.com/go-kit/kit"]
  sumVersion = "v0.9.0"
  ["github.com/go-kit/kit".fetch]
    type = "git"
    url = "https://github.com/go-kit/kit"
    rev = "150a65a7ec6156b4b640c1fd55f26fd3d475d656"
    sha256 = "09038mnw705h7isbjp8dzgp2i04bp5rqkmifxvwc5xkh75s00qpw"

["github.com/go-logfmt/logfmt"]
  sumVersion = "v0.4.0"
  ["github.com/go-logfmt/logfmt".fetch]
    type = "git"
    url = "https://github.com/go-logfmt/logfmt"
    rev = "07c9b44f60d7ffdfb7d8efe1ad539965737836dc"
    sha256 = "06smxc112xmixz78nyvk3b2hmc7wasf2sl5vxj1xz62kqcq9lzm9"

["github.com/go-stack/stack"]
  sumVersion = "v1.8.0"
  ["github.com/go-stack/stack".fetch]
    type = "git"
    url = "https://github.com/go-stack/stack"
    rev = "2fee6af1a9795aafbe0253a0cfbdf668e1fb8a9a"
    sha256 = "0wk25751ryyvxclyp8jdk5c3ar0cmfr8lrjb66qbg4808x66b96v"

["github.com/gogo/protobuf"]
  sumVersion = "v1.1.1"
  ["github.com/gogo/protobuf".fetch]
    type = "git"
    url = "https://github.com/gogo/protobuf"
    rev = "636bf0302bc95575d69441b25a2603156ffdddf1"
    sha256 = "1525pq7r6h3s8dncvq8gxi893p2nq8dxpzvq0nfl5b4p6mq0v1c2"

["github.com/golang/protobuf"]
  sumVersion = "v1.3.2"
  ["github.com/golang/protobuf".fetch]
    type = "git"
    url = "https://github.com/golang/protobuf"
    rev = "6c65a5562fc06764971b7c5d05c76c75e84bdbf7"
    sha256 = "1k1wb4zr0qbwgpvz9q5ws9zhlal8hq7dmq62pwxxriksayl6hzym"

["github.com/google/go-cmp"]
  sumVersion = "v0.3.1"
  ["github.com/google/go-cmp".fetch]
    type = "git"
    url = "https://github.com/google/go-cmp"
    rev = "2d0692c2e9617365a95b295612ac0d4415ba4627"
    sha256 = "1caw49i0plkjxir7kdf5qhwls3krqwfmi7g4h392rdfwi3kfahx1"

["github.com/google/gofuzz"]
  sumVersion = "v1.0.0"
  ["github.com/google/gofuzz".fetch]
    type = "git"
    url = "https://github.com/google/gofuzz"
    rev = "f140a6486e521aad38f5917de355cbf147cc0496"
    sha256 = "0qz439qvccm91w0mmjz4fqgx48clxdwagkvvx89cr43q1d4iry36"

["github.com/json-iterator/go"]
  sumVersion = "v1.1.8"
  ["github.com/json-iterator/go".fetch]
    type = "git"
    url = "https://github.com/json-iterator/go"
    rev = "03217c3e97663914aec3faafde50d081f197a0a2"
    sha256 = "1kbp9fj6fxfql0ir59zb6v68l4bpwlmk76xm8vaikw1hp6y9bcss"

["github.com/julienschmidt/httprouter"]
  sumVersion = "v1.2.0"
  ["github.com/julienschmidt/httprouter".fetch]
    type = "git"
    url = "https://github.com/julienschmidt/httprouter"
    rev = "348b672cd90d8190f8240323e372ecd1e66b59dc"
    sha256 = "1k8bylc9s4vpvf5xhqh9h246dl1snxrzzz0614zz88cdh8yzs666"

["github.com/konsorten/go-windows-terminal-sequences"]
  sumVersion = "v1.0.1"
  ["github.com/konsorten/go-windows-terminal-sequences".fetch]
    type = "git"
    url = "https://github.com/konsorten/go-windows-terminal-sequences"
    rev = "5c8c8bd35d3832f5d134ae1e1e375b69a4d25242"
    sha256 = "1lchgf27n276vma6iyxa0v1xds68n2g8lih5lavqnx5x6q5pw2ip"

["github.com/kr/logfmt"]
  sumVersion = "v0.0.0-20140226030751-b84e30acd515"
  ["github.com/kr/logfmt".fetch]
    type = "git"
    url = "https://github.com/kr/logfmt"
    rev = "b84e30acd515aadc4b783ad4ff83aff3299bdfe0"
    sha256 = "02ldzxgznrfdzvghfraslhgp19la1fczcbzh7wm2zdc6lmpd1qq9"

["github.com/matttproud/golang_protobuf_extensions"]
  sumVersion = "v1.0.1"
  ["github.com/matttproud/golang_protobuf_extensions".fetch]
    type = "git"
    url = "https://github.com/matttproud/golang_protobuf_extensions"
    rev = "c12348ce28de40eed0136aa2b644d0ee0650e56c"
    sha256 = "1d0c1isd2lk9pnfq2nk0aih356j30k3h1gi2w0ixsivi5csl7jya"

["github.com/modern-go/concurrent"]
  sumVersion = "v0.0.0-20180306012644-bacd9c7ef1dd"
  ["github.com/modern-go/concurrent".fetch]
    type = "git"
    url = "https://github.com/modern-go/concurrent"
    rev = "bacd9c7ef1dd9b15be4a9909b8ac7a4e313eec94"
    sha256 = "0s0fxccsyb8icjmiym5k7prcqx36hvgdwl588y0491gi18k5i4zs"

["github.com/modern-go/reflect2"]
  sumVersion = "v1.0.1"
  ["github.com/modern-go/reflect2".fetch]
    type = "git"
    url = "https://github.com/modern-go/reflect2"
    rev = "94122c33edd36123c84d5368cfb2b69df93a0ec8"
    sha256 = "06a3sablw53n1dqqbr2f53jyksbxdmmk8axaas4yvnhyfi55k4lf"

["github.com/mwitkow/go-conntrack"]
  sumVersion = "v0.0.0-20161129095857-cc309e4a2223"
  ["github.com/mwitkow/go-conntrack".fetch]
    type = "git"
    url = "https://github.com/mwitkow/go-conntrack"
    rev = "cc309e4a22231782e8893f3c35ced0967807a33e"
    sha256 = "0nbrnpk7bkmqg9mzwsxlm0y8m7s9qd9phr1q30qlx2qmdmz7c1mf"

["github.com/pkg/errors"]
  sumVersion = "v0.8.1"
  ["github.com/pkg/errors".fetch]
    type = "git"
    url = "https://github.com/pkg/errors"
    rev = "ba968bfe8b2f7e042a574c888954fccecfa385b4"
    sha256 = "0g5qcb4d4fd96midz0zdk8b9kz8xkzwfa8kr1cliqbg8sxsy5vd1"

["github.com/pmezard/go-difflib"]
  sumVersion = "v1.0.0"
  ["github.com/pmezard/go-difflib".fetch]
    type = "git"
    url = "https://github.com/pmezard/go-difflib"
    rev = "792786c7400a136282c1664665ae0a8db921c6c2"
    sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw"

["github.com/prometheus/client_golang"]
  sumVersion = "v1.3.0"
  ["github.com/prometheus/client_golang".fetch]
    type = "git"
    url = "https://github.com/prometheus/client_golang"
    rev = "c42bebe5a5cddfc6b28cd639103369d8a75dfa89"
    sha256 = "0cmyvyvss8bssnjasxm35aljc8hy8q8hrqw7z0d9pjk56f7g6a3n"

["github.com/prometheus/client_model"]
  sumVersion = "v0.1.0"
  ["github.com/prometheus/client_model".fetch]
    type = "git"
    url = "https://github.com/prometheus/client_model"
    rev = "d1d2010b5beead3fa1c5f271a5cf626e40b3ad6e"
    sha256 = "1hcqnx9szzk3rs49nbzlynskll01l94vamwcly5yvjdfk0lkm9ml"

["github.com/prometheus/common"]
  sumVersion = "v0.7.0"
  ["github.com/prometheus/common".fetch]
    type = "git"
    url = "https://github.com/prometheus/common"
    rev = "287d3e634a1e550c9e463dd7e5a75a422c614505"
    sha256 = "0a8yc0ppp50479sdhg9zbjnc4p7sqs6pdzvp27wzvccagbcy310c"

["github.com/prometheus/procfs"]
  sumVersion = "v0.0.8"
  ["github.com/prometheus/procfs".fetch]
    type = "git"
    url = "https://github.com/prometheus/procfs"
    rev = "6d489fc7f1d9cd890a250f3ea3431b1744b9623f"
    sha256 = "076wblhz8fjdc73fmz1lg0hafbwg1xv8hszm78lbg9anjpfgacvq"

["github.com/sirupsen/logrus"]
  sumVersion = "v1.4.2"
  ["github.com/sirupsen/logrus".fetch]
    type = "git"
    url = "https://github.com/sirupsen/logrus"
    rev = "839c75faf7f98a33d445d181f3018b5c3409a45e"
    sha256 = "087k2lxrr9p9dh68yw71d05h5g9p5v26zbwd6j7lghinjfaw334x"

["github.com/stretchr/objx"]
  sumVersion = "v0.1.1"
  ["github.com/stretchr/objx".fetch]
    type = "git"
    url = "https://github.com/stretchr/objx"
    rev = "477a77ecc69700c7cdeb1fa9e129548e1c1c393c"
    sha256 = "0iph0qmpyqg4kwv8jsx6a56a7hhqq8swrazv40ycxk9rzr0s8yls"

["github.com/stretchr/testify"]
  sumVersion = "v1.3.0"
  ["github.com/stretchr/testify".fetch]
    type = "git"
    url = "https://github.com/stretchr/testify"
    rev = "ffdc059bfe9ce6a4e144ba849dbedead332c6053"
    sha256 = "0wjchp2c8xbgcbbq32w3kvblk6q6yn533g78nxl6iskq6y95lxsy"

["golang.org/x/crypto"]
  sumVersion = "v0.0.0-20190308221718-c2843e01d9a2"
  ["golang.org/x/crypto".fetch]
    type = "git"
    url = "https://go.googlesource.com/crypto"
    rev = "c2843e01d9a2bc60bb26ad24e09734fdc2d9ec58"
    sha256 = "01xgxbj5r79nmisdvpq48zfy8pzaaj90bn6ngd4nf33j9ar1dp8r"

["golang.org/x/net"]
  sumVersion = "v0.0.0-20190613194153-d28f0bde5980"
  ["golang.org/x/net".fetch]
    type = "git"
    url = "https://go.googlesource.com/net"
    rev = "d28f0bde5980168871434b95cfc858db9f2a7a99"
    sha256 = "18xj31h70m7xxb7gc86n9i21w6d7djbjz67zfaljm4jqskz6hxkf"

["golang.org/x/sync"]
  sumVersion = "v0.0.0-20190911185100-cd5d95a43a6e"
  ["golang.org/x/sync".fetch]
    type = "git"
    url = "https://go.googlesource.com/sync"
    rev = "cd5d95a43a6e21273425c7ae415d3df9ea832eeb"
    sha256 = "1nqkyz2y1qvqcma52ijh02s8aiqmkfb95j08f6zcjhbga3ds6hds"

["golang.org/x/sys"]
  sumVersion = "v0.0.0-20191220142924-d4481acd189f"
  ["golang.org/x/sys".fetch]
    type = "git"
    url = "https://go.googlesource.com/sys"
    rev = "d4481acd189fe3601058b16da7382c3dba7157a8"
    sha256 = "08j1j8ajaqq3ybs5wz223x7l44d2m9vjy6wdc6q40rpz3i4j4085"

["golang.org/x/text"]
  sumVersion = "v0.3.0"
  ["golang.org/x/text".fetch]
    type = "git"
    url = "https://go.googlesource.com/text"
    rev = "f21a4dfb5e38f5895301dc265a8def02365cc3d0"
    sha256 = "0r6x6zjzhr8ksqlpiwm5gdd7s209kwk5p4lw54xjvz10cs3qlq19"

["golang.org/x/xerrors"]
  sumVersion = "v0.0.0-20200804184101-5ec99f83aff1"
  ["golang.org/x/xerrors".fetch]
    type = "git"
    url = "https://go.googlesource.com/xerrors"
    rev = "5ec99f83aff198f5fbd629d6c8d8eb38a04218ca"
    sha256 = "1dbzc3gmf2haazpv7cgmv97rq40g2xzwbglc17vas8dwhgwgwrzb"

["gopkg.in/alecthomas/kingpin.v2"]
  sumVersion = "v2.2.6"
  ["gopkg.in/alecthomas/kingpin.v2".fetch]
    type = "git"
    url = "https://gopkg.in/alecthomas/kingpin.v2"
    rev = "947dcec5ba9c011838740e680966fd7087a71d0d"
    sha256 = "0mndnv3hdngr3bxp7yxfd47cas4prv98sqw534mx7vp38gd88n5r"

["gopkg.in/check.v1"]
  sumVersion = "v0.0.0-20161208181325-20d25e280405"
  ["gopkg.in/check.v1".fetch]
    type = "git"
    url = "https://gopkg.in/check.v1"
    rev = "20d25e2804050c1cd24a7eea1e7a6447dd0e74ec"
    sha256 = "0k1m83ji9l1a7ng8a7v40psbymxasmssbrrhpdv2wl4rhs0nc3np"

["gopkg.in/yaml.v2"]
  sumVersion = "v2.2.2"
  ["gopkg.in/yaml.v2".fetch]
    type = "git"
    url = "https://gopkg.in/yaml.v2"
    rev = "51d6538a90f86fe93ac480b35f37b2be17fef232"
    sha256 = "01wj12jzsdqlnidpyjssmj0r4yavlqy7dwrg7adqd8dicjc4ncsa"
